apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: example-policy
spec:
  endpointSelector:
    matchLabels:
      app: frontend
  egress:
  - toEndpoints:
      - matchLabels:
          app: backend
    toPorts:
      - ports:
          - port: "80"
            protocol: TCP
